version: '3'

volumes:
  pg_data:
  static:

services:
  
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: gera1311/taski_backend
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
    volumes:
      - static:/backend_static
  
  frontend:
    env_file: .env
    image: gera1311/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  gateway:
    image: gera1311/taski_gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    