# Имя workflow
name: Main Taski Workflow
# Перечень событий тригеров, при которых должен запускаться workflow
on:
  push:
    branches:
      - main
# Перечень задач
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 # Берем готовое решение из библиотеки GitHub Actions
      # Выполняем команду tree в текущей директории
      - name: Print project tree
       run: tree .